spring:
  messages:
    basename: config.login  # 设置国际化配置文件路径
  devtools:
    restart:
      enabled: true #  设置开启热部署
  freemarker:
    cache: false # 页面不加载缓存，修改后直接生效
  thymeleaf:
    cache: false  # 禁用thymeleaf页面缓存
  #    数据源配置
  datasource: # 基本配置
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.111:3308/wangbo
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #    数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  #      web-stat-filter:
  #          enabled: false
  #    schema:
  #      - classpath:test01.sql
  #      - classpath:test02.sql
  #    initialization-mode: always

  #  设置jpa的相关配置
  jpa:
    hibernate:
      ddl-auto: update  # 定义数据表的生成策略
    show-sql: true  # 设置控制台显示每次操作生成的SQL语句

#debug: true # 开启热部署

# mybatis的相关配置
mybatis:
  #  注册mybatis全局配置文件的路径
  config-location: classpath:mybatis/mybatis-config.xml
  #  注册mybatis的mapper接口映射文件的路径
  mapper-locations: classpath:mybatis/mapper/*.xml
